# Generated by Django 5.1.4 on 2025-01-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('entertainment', 'Rozrywka'), ('regular', 'Zadania zwykłe'), ('mandatory', 'Obowiązkowe zadania')], default='regular', max_length=20),
        ),
    ]
